### ISSUE TITLE
MacBook Pro (13 inch, 2019) & Acer XV273KPbmiipphzx

### ISSUE THREAD

**Issue by gma2th** [tonsky/tonsky.github.io#19]
MacBook Pro (13 inch, 2019) with Acer XV273KPbmiipphzx has refresh rate of 30 Hz maximum.
<img width="669" alt="Screenshot 2021-06-01 at 14 20 29" src="https://user-images.githubusercontent.com/7457957/120322280-86830e80-c2e4-11eb-93a8-d853fd779dfc.png">
<img width="592" alt="Screenshot 2021-06-01 at 14 17 16" src="https://user-images.githubusercontent.com/7457957/120321959-32782a00-c2e4-11eb-9a6f-9599298d2c8a.png">
<img width="752" alt="Screenshot 2021-06-01 at 14 22 25" src="https://user-images.githubusercontent.com/7457957/120322540-cd710400-c2e4-11eb-875b-2f390d738ccc.png">

**Comment by tonsky** [comment]
That’s terrible :(
