### ISSUE TITLE
iMac 202 with Radeon Pro 5700 XT and an Asus PA32UCG DOES NOT WORK

### ISSUE THREAD

**Issue by VoxelAgentSimon** [tonsky/tonsky.github.io#26]
hey just leaving an update about compatibility; 

I've tried this combo:
- Intel i9 iMac 2020 with Radeon Pro 5700 XT 
- Asus PA32UCG monitor
- connected via Thunderbolt cable (40Gbps) provided with the Asus monitor

Unfortunately it does not seem to work.  Here's my system info - it doesn't show the 120hz offering like the screenshot you provide on the website.
https://drive.google.com/file/d/15k4a1o9weXrzaCXmWO9XhnhWcOct0BPk/view?usp=sharing

Side-note; you don't have any mention of iMacs on the website - is it known that Intel iMacs will never support 120hz? Would be good to share more info it's available.  This website suggests it's not possible https://everymac.com/systems/apple/imac/specs/imac-core-i9-3.6-10-core-27-inch-retina-5k-2020-20-2-specs.html 
quote from the everymac site; "_*This model can simultaneously support the internal display at full native resolution and up to one 6016x3384 (6K) external display at 60 Hz with support for 1 billion colors; one 5120x2880 (5K) external display at 60 Hz with support for 1 billion colors; two 3840x2160 (4K UHD) external displays at 60 Hz with support for 1 billion colors; or two 4096x2304 (4K) external displays at 60 Hz with support for millions of colors. It supports both extended desktop (second workspace) and video mirroring (internal display duplicated on the external display) modes._"

Thanks,
Simon

**Comment by tonsky** [comment]
Thank you! That looks like a great monitor, shame it doesn’t work.

As for iMac / 120 Hz compatibility, it’s hard to tell. The text they have on everymac.com looks like a copy-paste from Apple website. It seems accurate in terms of what _does_ work, but it’s certainly incomplete. For some reason Apple never officialy lists 120 Hz support on any of its Macs, but some monitors do work with some Macs. Hence my own list

**Comment by VoxelAgentSimon** [comment]
Yeah I really appreciate you creating this list! Thank you so much.

I can provide a bit more info on this setup… the good news is that it works
at 4K 120hz in windows with the AMD software installed. That was quite a
relief to see it working at all.

But I could not figure out any way to get 120hz in OS X. I guess I should
try a lower res, like 1080p and check if that offers a higher frame rate
option.

I’ve also bought a few other cables to try just in case that might help.

Cheers!
Simon.

**Comment by VoxelAgentSimon** [comment]
I just stumbled across your blog post https://tonsky.me/blog/monitors/.
Great article!

Now I feel really stupid though, I hadn't seen your instructions before
about how to make 120hz appear as an option in OS X system preferences. You
cover it in the blog post, but not on the monitor compatibility page -
perhaps you could add the instructions for how to expose the refresh rate
settings on the compatibility page because I'm sure there's many dummies
out there like me who don't know how to do the dance with OS X.

So fortunately the good news is that the PA32UCG works at 4k 120hz 30 bit
colour buffer on OS X, and also in Bootcamp! I just hadn't configured it
right before.
https://drive.google.com/file/d/1yXXmwXkRe8WoHZYbUS0mQQEUkRIoFUms/view?usp=sharing

Please update the listing.

Regards,
Simon

**Comment by tonsky** [comment]
Great! So happy for you!
