### ISSUE TITLE
New Monitor to Add to List

### ISSUE THREAD

**Issue by bradleyandrew** [tonsky/tonsky.github.io#60]
Hey Tonsky,

Thanks for your work building the monitor compatibility list, it helped me out when selecting monitor for my Mac Studio. I've never really done a PR and couldn't quite figure it out, I assume I needed to fork the repo but that seemed like overkill just to pass on information for new compatibility.

Anyway, Mac Studio M1 Ultra is working a-okay with 2x Gigabyte M32U Displays at UHD 144Hz. Connected via TB3 to DisplayPort 1.4 Cable. Please see screenshots below.

<img width="593" alt="tonsky-01" src="https://user-images.githubusercontent.com/66546729/158975281-d936e2db-ad7f-4819-8e05-c9bf27384785.png">

<img width="611" alt="tonsky-02" src="https://user-images.githubusercontent.com/66546729/158974646-326712bb-f01b-4055-8a59-e034cc2b1c1d.png">

Thanks for your work, it's kindly appreciated!

**Comment by tonsky** [comment]
Thank you!
