### ISSUE TITLE
Samsung G70A compatibility

### ISSUE THREAD

**Issue by laxu** [tonsky/tonsky.github.io#74]
I couldn't figure out where I should add the data to make a pull request so I decided to make an issue instead. Please add some instructions as there's a lot of code unrelated to display compatibility!

Without further ado:
![Screenshot 2022-08-25 at 12 10 27](https://user-images.githubusercontent.com/987972/186624807-59518950-cbb4-469b-af58-87b0de1e9f17.png)

The Samsung G70A 28" 4K 144 Hz display does NOT work with the 2019 Intel Macbook Pro at above 4K 60 Hz speeds. 

Tested using a CableMatters USB-C to DP 1.4 adapter and then a DP cable connected to the monitor. I also tested this same adapter through my PC's 2080 Ti's USB-C port and get full 4K 144 Hz so the limitation is entirely on the Mac.

**Comment by tonsky** [comment]
Thanks! Added
