### ISSUE TITLE
 Confirmed Gigabyte AORUS FI32U 4k @ 144hz

### ISSUE THREAD

**Issue by strangebutohwell** [tonsky/tonsky.github.io#76]
(I dont know how to do a pull request but wanted to submit this:)

<img width="603" alt="Screen Shot 2022-08-30 at 10 09 11 PM" src="https://user-images.githubusercontent.com/61894306/187577177-cc7e3b13-ec93-4b75-acea-b83fc6a7c77b.png">

Confirmed Gigabyte AORUS FI32U 4k @ 120hz, 144hz, or Variable Refresh Rate (48-144hz)  on MacBook Pro 14" M1 Pro with USB-C or TB4 connection. KVM and HDR features work as well.

**Comment by tonsky** [comment]
Thanks! Added

**Comment by AlexAleksandrov** [comment]
@strangebutohwell can you please share how you achieved that? What cable/os x version/os x settings/ monitor settings? 
Trying to setup similar tech and failing

**Comment by strangebutohwell** [comment]
> 

Using a MacBook Pro M1 Pro, latest macOS.

This is the cable I used:
https://smile.amazon.com/gp/product/B0827CR8GW/ref=ppx_yo_dt_b_search_asin_title

That cable works both when plugged directly into the MacBook's ports, as well as when plugged into the CalDigit ThunderBolt 4 Element Hub. The Hub is connected to the MacBook with a TB4 cable. 

I didn't have to change any settings to get it to work. If there are specific settings you're interested in on the monitor, I can check when I get home.

**Comment by AlexAleksandrov** [comment]
@strangebutohwell Thank you, cable which comes with a monitor was not enough, bought good quality cable - display port to usb-c, and now I can confirm that it provides 4k 144hz with HDR
