### ISSUE TITLE
Update 2019 16in mbp LG C1 48 support

### ISSUE THREAD

**Issue by Mravuri96** [tonsky/tonsky.github.io#77]
I have 4k 120hz with HDR on 2021 LG C1 48in working on my 2019 16in mbp.

![image](https://user-images.githubusercontent.com/28457922/189457046-07e76d04-69d6-4734-b8ea-c5a38764853c.png)

![image](https://user-images.githubusercontent.com/28457922/189457053-835a49f3-91ba-4c6d-ab18-4b1490da2377.png)

![image](https://user-images.githubusercontent.com/28457922/189457196-7aafa2a0-fc1f-4e1f-afec-1f3c354de7d3.png)

![20220909_162033](https://user-images.githubusercontent.com/28457922/189458517-18eaedbb-32dc-4635-9f71-31be2d48c72f.jpg)
---
HDR signal
![hdr](https://user-images.githubusercontent.com/28457922/189458608-b5194fa2-8db7-4be3-a5bd-b4b0cf75612f.jpg)

![image](https://user-images.githubusercontent.com/28457922/189459182-804ab632-7e9c-4920-a026-6b4ddff8c18d.png)

---
Bootcamp windows
![image](https://user-images.githubusercontent.com/28457922/189461474-8772efbe-166f-4ef9-b843-fea70891bb07.png)

![image](https://user-images.githubusercontent.com/28457922/189461892-c5571345-d432-4e16-8d92-ae3f7e3ddc53.png)

All supported refresh rates at 3840x2160 
![image](https://user-images.githubusercontent.com/28457922/189461909-03618c1f-def2-4024-b0e1-155bfcf8b8b9.png)

Working hdr only at 60hz on windows. macos is allowing 4k 120 with hdr
HDR/SDR brightness balance slider is also working
![image](https://user-images.githubusercontent.com/28457922/189461823-b8083c8d-7089-401c-a050-20e639750597.png)

**Comment by tonsky** [comment]
But how? What cable?

**Comment by Mravuri96** [comment]
[Cable](https://en.j5create.com/products/jcc157)

**Comment by tonsky** [comment]
Thanks! This is HUGE

**Comment by Mravuri96** [comment]
@tonsky I believe that the wrong model has been updated, I actually have the 5500m.
![image](https://user-images.githubusercontent.com/28457922/190021546-2ec91e61-7674-47a3-a3b4-f38b04397655.png)

**Comment by tonsky** [comment]
unfortunately cable makes no difference on M1 mac. 4K@120Hz via HDMI still doesn’t work :(
