### ISSUE TITLE
Japannext GX28 4k/144hz supported with mac studio (usb-c)

### ISSUE THREAD

**Issue by apayen** [tonsky/tonsky.github.io#78]
Hi there,

I was able to connect Japannext GX28 monitor (JN-280IPS144UHDR-C65W) to my mac studio (M1 max) using the usb-c-to-c cable provided with the screen and configure settings to use 4k hdr 144hz. My mac is on Ventura's latest beta.

https://japannext.net/gx28/

**Comment by tonsky** [comment]
Thanks!
